### ISSUE TITLE
Compile with reference;

### ISSUE THREAD

**Issue by nsklyarov** [jordwalke/CommonML#20]
How compile with reference to the Unix library?

Now when compiling get this error message:
File "_none_", line 1:
Error: No implementations provided for the following modules: Unix referenced from ./path

compile so:
node ./node_modules/CommonML/build.js --compiler=native

**Comment by jordwalke** [comment]
You closed this, did you find the answer (if so, could you share?) There's probably a flag you ended up passing to get it to work (and you can specify those flags in the package.json).
